version: 2.0
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - checkout

      - run:
          command: pip install -r requirements.txt
          name: Install dependencies

#      - run: apt-get update
#      - run: apt-get install java
#
#      - run: wget -O /tmp/selenium-server-standalone-2.45.0.jar "http://selenium-release.storage.googleapis.com/2.45/selenium-server-standalone-2.45.0.jar"
#
#      - run:
#          command: java -jar /tmp/selenium-server-standalone-2.45.0.jar
#          background: true

      - run:
          command: setsid python -m SimpleHTTPServer 8080
          pwd: /gordon-test/server-root
          background: true

      - run:
          name: make some files
          command: |
            mkdir -p /tmp/my_workspace
            echo "first artifact" > /tmp/my_workspace/first
            echo "second artifact" > /tmp/my_workspace/second
            mkdir -p /tmp/my_workspace/python/foo
            cp hello.py /tmp/my_workspace/python/
            cp hello.py /tmp/my_workspace/python/foo

      - persist_to_workspace:
          root: /tmp/my_workspace
          paths:
            - "*"
            - python/*

      - store_artifacts:
          path: /tmp/my_workspace
          destination: text-data

  test:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - attach_workspace:
          at: /tmp/my_workspace

      - run:
          command: echo "third artifact!!" > /tmp/my_workspace/third
          pwd: /

      - persist_to_workspace:
          root: /tmp/my_workspace
          paths:
            - third

  deploy:
    docker:
      - image: python:2.7
    working_directory: /gordon-test
    steps:
      - run:
          command: echo "deploying! (not really) "
          pwd: /

      - run:
          name: "Workflow workspace env vars"
          command: |
            echo "CIRCLE_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID}"
            echo "CIRCLE_WORKFLOW_WORKSPACE_ID=${CIRCLE_WORKFLOW_WORKSPACE_ID}"
            echo "CIRCLE_WORKFLOW_JOB_ID=${CIRCLE_WORKFLOW_JOB_ID}"
            echo "CIRCLE_WORKFLOW_UPSTREAM_JOB_IDS=${CIRCLE_WORKFLOW_UPSTREAM_JOB_IDS}"
          pwd: /

      - attach_workspace:
          at: my_workspace

      - run: find /gordon-test/my_workspace

      - run: cat my_workspace/first

      - run: cat my_workspace/second

      - run: cat my_workspace/third

      - run: python -c "import os,sys; sys.exit(int(os.environ['CIRCLE_BUILD_NUM']) % 2)"

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
