version: 2.0
jobs:
  build:
    docker:
      - image: python:2.7
    working_directory: ~root/gordon-test
    steps:
      - checkout

      - run: python -c "import os,sys; sys.exit(int(os.environ['CIRCLE_BUILD_NUM']) % 2)"
