version: 2.0
jobs:
  build:
    docker:
      - image: alpine:3.6
    working_directory: /gordon-test
    steps:
      - run:
          name: Install deps
          command: apk update; apk add git ca-certificates

      - checkout

      - run:
          name: make some files
          command: |
            mkdir -p /tmp/my_workspace
            echo "first artifact" > /tmp/my_workspace/first
            echo "second artifact" > /tmp/my_workspace/second
            mkdir -p /tmp/my_workspace/python
            echo "print \"hello world\"" > /tmp/my_workspace/python/hello.py
            cp /tmp/my_workspace/python/hello.py /tmp/my_workspace/python/.hidden

      - persist_to_workspace:
          root: /tmp/my_workspace
          paths:
            - "*"

      - store_artifacts:
          path: /tmp/my_workspace
          destination: text-data

  test:
    docker:
      - image: alpine:3.6
    working_directory: /gordon-test
    steps:
      - run:
          name: Install deps
          command: apk update; apk add git ca-certificates

      - attach_workspace:
          at: /tmp/my_workspace

      - run:
          command: echo "third artifact!!" > /tmp/my_workspace/third
          pwd: /

      - persist_to_workspace:
          root: /tmp/my_workspace
          paths:
            - third

  deploy:
    docker:
      - image: alpine:3.6
    working_directory: /gordon-test
    steps:
      - run:
          name: Install deps
          command: apk update; apk add git ca-certificates

      - run:
          command: echo "deploying! (not really) "
          pwd: /

      - run:
          name: "Workflow workspace env vars"
          command: |
            echo "CIRCLE_WORKFLOW_ID=${CIRCLE_WORKFLOW_ID}"
            echo "CIRCLE_WORKFLOW_WORKSPACE_ID=${CIRCLE_WORKFLOW_WORKSPACE_ID}"
            echo "CIRCLE_WORKFLOW_JOB_ID=${CIRCLE_WORKFLOW_JOB_ID}"
            echo "CIRCLE_WORKFLOW_UPSTREAM_JOB_IDS=${CIRCLE_WORKFLOW_UPSTREAM_JOB_IDS}"
          pwd: /

      - attach_workspace:
          at: my_workspace

      - run: find /gordon-test/my_workspace

      - run: cat my_workspace/first

      - run: cat my_workspace/second

      - run: cat my_workspace/third

      - run: python -c "import os,sys; sys.exit(int(os.environ['CIRCLE_BUILD_NUM']) % 2)"

workflows:
  version: 2
  build-n-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test

